# Generated by Django 3.1.1 on 2022-02-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=122)),
                ('company_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=122)),
                ('job_description', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('created_at', models.DateTimeField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
